### Properties
@endpoint=http://localhost:8083
@connector-name=s3-sink-local

### Get Connectors Status
GET {{endpoint}}/connectors

### Get Connector Status
GET {{endpoint}}/connectors/{{connector-name}}/status

### Create or Modify Connector
PUT {{endpoint}}/connectors/{{connector-name}}/config
Content-Type: application/json

{
  "connector.class": "io.confluent.connect.s3.S3SinkConnector",
  "topics": "examples-s3-sink",
  "tasks.max": "1",

  "key.converter": "org.apache.kafka.connect.storage.StringConverter",
  "value.converter": "org.apache.kafka.connect.json.JsonConverter",
  "value.converter.schemas.enable": "false",

  "s3.region": "ap-northeast-2",
  "s3.bucket.name": "kafka-example-bucket",
  "s3.part.size": "5242880",
  "storage.class": "io.confluent.connect.s3.storage.S3Storage",
  "topics.dir": "backup",
  "aws.access.key.id": "user",
  "aws.secret.access.key": "secret",

  "format.class": "io.confluent.connect.s3.format.json.JsonFormat",
  "flush.size": "500",
  "rotate.schedule.interval.ms": "60000",

  "partitioner.class": "io.confluent.connect.storage.partitioner.TimeBasedPartitioner",
  "path.format": "'year'=YYYY/'month'=MM/'day'=dd/'hour'=HH",
  "partition.duration.ms": "3600000",
  "locale": "ko_KR",
  "timezone": "Asia/Seoul",
  "timestamp.extractor": "Record"
}

### Pause Connector
PUT {{endpoint}}/connectors/{{connector-name}}/pause

### Restart Connector
PUT {{endpoint}}/connectors/{{connector-name}}/restart